### ISSUE TITLE
Creating sub modules for organizing

### ISSUE THREAD

**Issue by rleonid** [mmottl/lacaml#12]
I sometimes find it a bit overwhelming navigating all of the functions in Lacaml, and wish for a little bit more organization. I'd like to propose a couple of suggestions, they're entirely optional, just to get a discussion started and give some possibilities.

1. Group the functions in `Lacaml_S` (and `Lacaml_D`, `Lacaml_C` ...) into submodules `Blas1`, `Blas2`, `Blas3` and `Lapack_ar`, `Lapack_ls`, `Lapack_svd` (... etc, I don't really like the 'simple' and 'expert' driver breakdowns but I'm not certain this would be much better).
2. In `Vec` group the `Lacaml_float64.vec -> Lacaml_float64.vec`  functions (`exp`, `exp1m`, `sin`, `sqrt` ) into a sub module such as `Op` (for operations) ? 
3. The special matrix functions  (`hilbert`, `hankel` ...) into a sub module `Special` .

I understand that to support backward compatibility maybe we'd have to setup some other module not to break existing code.

**Comment by mmottl** [comment]
I agree that Lacaml, which is very much organically grown, could benefit from better organization.  That said, I think it would be overly intrusive to users to change the API in such a major way.  Maybe it would be better to create a new standalone project for vector/matrix algebra, which tries to learn all the (good and bad) lessons from Lacaml and gets it right.  This library could still reuse much of Lacaml and, eventually, adopt the still needed code until it subsumes most of the functionality and can do without Lacaml.  At that point new users or ones willing to adapt existing code might want to switch.

This would be no small undertaking.  Lacaml is already pretty large, and it's probably decent enough for most users (including me).  But if you like a challenge... :wink:

**Comment by rleonid** [comment]
Those are fair points. I figured any such change would be too onerous on the current user space and probably require a new API. I think a whole new standalone project is a good idea, and one that I'm tangentially pursing. This issue was a suggestion to help bridge to that ideal state.

If no one else has any other opinions on the matter, feel free to close this issue. If time allows, I'll try to create and work with the modules that I'm proposing in a separate branch/fork, for educational sake :)

**Comment by mmottl** [comment]
Indeed, it might actually be a good idea to start such a project as a fork/branch to Lacaml, just for experimentation.  Once you see what would work better, you can always factor that out into a "clean" project.
