### ISSUE TITLE
lacaml on Windows

### ISSUE THREAD

**Issue by kkirstein** [mmottl/lacaml#17]
Hi,

has anybody successfully installed lacaml on Windows7 (64bit)?
I'm trying to do so with `opam install lacaml` and end with missing symbols from the fortran runtime, e.g. `_gfortran_concat_string`. `libgfortran-3.dll` is on my path. I have a cygwin environment with a x86_64-w64-mingw32 toolchain (gcc & gfortran). Maybe I have to add some linking options to `setup.conf`?
The toolchain and opam seem to be setup correctly, as I can successfully install packages like lablgtk.

Thanks in advance for any hints,
Kay-Uwe

P.S: I'm a newbie at ocaml & opam, so please bare with me, if I missed something obvious...

[lacaml.7.2.6_build_output.zip](https://github.com/mmottl/lacaml/files/197249/lacaml.7.2.6_build_output.zip)

**Comment by mmottl** [comment]
I'm afraid, but I can't help much with Windows issues.  If there are missing symbols, I usually try to find (grep for) them in the relevant Fortran libraries.  Maybe it's just a matter of linking with other or more of these libraries.  If you find a solution, please feel free to submit a patch.

**Comment by kkirstein** [comment]
I disabled building of the examples and now I can install lacaml. It gives a warning on a missing entry in `ld.conf` (did not know that this exists on cygwin). I will dig deeper and let you know if a patch will fix it.

**Comment by Chris00** [comment]
Thanks @kkirstein  Maybe you would like to help us setting up Appveyor continuous integration to avoid regressions in the future?   You can find an [example here](https://github.com/Chris00/ocaml-mindstorm).  It would be nice to have an MSVC build of Lacaml but that may not be that easy.

**Comment by kkirstein** [comment]
It looked like my lapack library was not linked properly. Rebuilding blas & lapack fixed most of the missing symbols (The remaining missing symbols should be fixed with proper preprocessor defs). Before submitting a patch, I have to do some more testing...
Having an Appveyor CI is a great idea, but we have to decide, which setup we would like to support, as there are several toolchains (more or less) supported for windows. You are mentioning MSVC, while personally, I prefer the mingw/cygwin setup provided by [OCaml for Windows (mingw-w64)](https://fdopen.github.io/opam-repository-mingw/), as it includes an opam setup that worked on my machine out-of-the-box.

Setting up an Appveyor environment should be possible, but might include some effort, as cygwinports does not have packages for blas & lapack. Maybe, I find some time to try it out...

**Comment by kkirstein** [comment]
ok, now I managed to build lacaml on my windows box. At the end the failure was mostly due to a broken blas/lapack lib (mixed static/dynamic linking). For the mingw64 toolchain some adjustement needs to be made in `_oasis`. I will send a respective PR...
