### ISSUE TITLE
Add some functions to make it easier to load matrices from CSV files

### ISSUE THREAD

**Issue by hammer** [mmottl/lacaml#2]
I've been importing matrices from CSV files using https://github.com/Chris00/ocaml-csv and would like to avoid passing my lists of lists into arrays before creating matrices. Here are some functions that would be useful to have for this use case:
* [ ] Mat.of_list/to_list
* [ ] Mat.of_col_vec_list/to_col_vec_list

**Comment by rleonid** [comment]
@hammer , I think that this issue can be closed.

**Comment by mmottl** [comment]
Closing...
