### ISSUE TITLE
exception from fortran can only be caught at top level

### ISSUE THREAD

**Issue by nilsbecker** [mmottl/lacaml#27]
i'm seeing strange behavior like below. i hope the structure is clear even though i have a ton of undefined symbols here.

```
let find_min x =
  let minim = nm_min teste ~x ~step_size:stepinit in
  try
    let success_steps = ref 0 in
    for i = 1 to maxit do
      Min.iterate minim;
      if Min.test_size minim 0.01
      then incr success_steps
      else success_steps := 0;
      if !success_steps >= succ_steps then raise @@ Converged i;
    done;
    minim
  with
  | Converged i ->
    (Format.printf "tolerance reached in step %d\n@." i;
    minim)
  | _ -> minim
```

in this function i try to catch all exceptions and always give back the current mutable minimizer object minim. sometimes the function to be minimized `teste` raises `Failure("Lacaml.D.potrf: leading minor of order 66 is not positive definite")` - and the catch-all case does not catch it!?

only when wrapping `find_min` on the top level i can catch it with `try find_min x with _ -> default_minim`

is it possible that lacaml can somehow smuggle this exception through? or am i doing something weird?

**Comment by nilsbecker** [comment]
this happens in byte or native code.

**Comment by nilsbecker** [comment]
4.04+flambda

**Comment by nilsbecker** [comment]
oh, and catching my own `Converged` exception works fine!

**Comment by mmottl** [comment]
The `try` statement comes after `let minim = ...` and hence cannot catch any exceptions escaping `nm_min` (which calls `teste`).

The particular error you are seeing indicates that either some matrix is not positive definite or is so ill-conditioned that it seems as if it were.  If it's just the latter, you may want to use the `jitter` parameter in your call to `potrf` to add a small quantity to the matrix diagonal to regularize it.

**Comment by nilsbecker** [comment]
D'oh! thanks. what happened was that usually exceptions are raised from `Min.iterate minim` inside the block. but indeed the `let minim` line also does some initial evaluations of the function before iterations start and that's where it raised. thanks for the hint about jitter - i feel a bit uneasy since i do not know how to judge what amount of jitter is small for my matrix.

**Comment by mmottl** [comment]
Maybe just computing the norm of the diagonal vector and taking a small fraction of it as jitter would work in most settings.  Alternatively, you could avoid `potrf` and instead calculate eigenvalues and eliminate directions with non-positive ones.

**Comment by nilsbecker** [comment]
ok, worth a try. or i just abort even at initialization with an outer try block.
