### ISSUE TITLE
building with alternative blas

### ISSUE THREAD

**Issue by nilsbecker** [mmottl/lacaml#29]
hi, i am troubleshooting on os x and have reason to believe that the Accelerate framework may be part of the problem. i therefore like to build lacaml with openblas instead. i installed openblas with homebrew and get this information:
```
For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/openblas/lib
    CPPFLAGS: -I/usr/local/opt/openblas/include
```
i assume i can change something in the _oasis file around line 86 to use that instead of the Accelerate framework. what exactly would i need to replace?

thanks for any help!

**Comment by mmottl** [comment]
You can change the `CCOpt` and `CCLib` flags anyway you like.  Just drop `-framework Accelerate` and replace it with the required linking flags.  The include flags should go in `CCOpt`.  Note that the plus in `CCOpt+` means that more flags are being added.

**Comment by nilsbecker** [comment]
thanks! i'm a bit of a newbie with this - so i would put a `CCOpt+` entry with `-I/usr/local/opt/openblas/include` and a `CCLib` entry with `-L/usr/local/opt/openblas/lib -lopenblas -llapack`? (i guessed the lib names from the filenames in the lib directory, without the `lib` prefix?

**Comment by mmottl** [comment]
This is probably right.  Not sure whether `-llapack` will work, you may have to add suitable paths for that, too.

**Comment by nilsbecker** [comment]
ok will try, a liblapack is present in the lib directory of openblas actually so i might work

**Comment by nilsbecker** [comment]
this seems to work fine, thanks. also, it seems to solve my problems with using lacaml together with parmap or functory, which work by forking. it might be that the Accelerate framework is incompatible with forking-based solutions to achieve parallelism, according to this:

https://mail.scipy.org/pipermail/numpy-discussion/2012-August/063589.html

(however i don't understand it well enough to know for sure)

**Comment by nilsbecker** [comment]
see also this thread:

https://github.com/rdicosmo/parmap/issues/18

**Comment by mmottl** [comment]
That's not surprising, combining forking and threads usually leads to disaster.  Another solution you could try is using `export VECLIB_MAXIMUM_THREADS=1`.  This should prevent Accelerate from using threads.

**Comment by nilsbecker** [comment]
hi again, now i'm trying to do the same thing on a linux cluster. this has atlas installed which does not allow me to set the number of threads dynamically. 

currently lacaml is built with atlas automatically. i tried the following: 

change in _oasis:
```
  # Linux specific: gnu99 is required to have nanosleep, others can just use c99 standard
  if system(linux) || system(linux_elf)
    CCOpt:      -g -std=gnu99 -O2 -fPIC -DPIC
    CCOpt+:      -I/usr/include/openblas
    CCLib:       -L/usr/lib64 -lopenblas -llapack
```

then `make clean && oasis setup && make build`. however this still builds binaries linked with atlas never with openblas. not sure why? example output of ldd:
```
ldd blas.native
	linux-vdso.so.1 =>  (0x00007ffc123f9000)
	libblas.so.3 => /usr/lib64/libblas.so.3 (0x00002b2a58153000)
	liblapack.so.3 => /usr/lib64/atlas/liblapack.so.3 (0x00002b2a583aa000)
	libm.so.6 => /lib64/libm.so.6 (0x00002b2a58bcc000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00002b2a58e50000)
	libc.so.6 => /lib64/libc.so.6 (0x00002b2a59054000)
	libgfortran.so.3 => /usr/lib64/libgfortran.so.3 (0x00002b2a593e9000)
	libf77blas.so.3 => /usr/lib64/atlas/libf77blas.so.3 (0x00002b2a596db000)
	libcblas.so.3 => /usr/lib64/atlas/libcblas.so.3 (0x00002b2a598fa000)
	/lib64/ld-linux-x86-64.so.2 (0x00002b2a57f31000)
	libatlas.so.3 => /usr/lib64/atlas/libatlas.so.3 (0x00002b2a59b1b000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b2a5a177000)
```

**Comment by nilsbecker** [comment]
i should note that in `_build/_log` all of the openblas include options show up in the gcc invocations. example:
```
# Target: src/utils_c.c, tags: { package(bigarray), package(bytes), annot, bin_annot, c, compile, debug, extension:c, file:src/utils_c.c, no_alias_deps, oasis_library_lacaml_ccopt, quiet, traverse }
/home/bq_nbecker/.opam/4.04.0+flambda/bin/ocamlfind ocamlc -g -ccopt -g -ccopt '-std=gnu99' -ccopt -O2 -ccopt -fPIC -ccopt -DPIC -ccopt -I/usr/include/openblas -ccopt -Wall -ccopt -pedantic -ccopt -Wextra -ccopt -Wunused -ccopt -Wno-long-long -package bytes -package bigarray -c src/utils_c.c
```

**Comment by mmottl** [comment]
My suggestion would be to first write your own test application in C and build it manually on the command line to make sure you understand how to properly link with the required libraries.  Once your C-application links as it it should, compare the linking command to what's happening in the Lacaml build logs.  It should be easy then to pass the correct flags.

**Comment by nilsbecker** [comment]
ok, so iiuc the general idea is not obviously wrong and it's more likely that the flags i'm using just don't work in this way. sigh. will have to dig deeper then.

**Comment by nilsbecker** [comment]
thanks for your suggestion, indeed by trying to compile an example from the openblas website it turned out that the `LD_LIBRARY_PATH` on the system was messed up. after fixing that, the procedure above worked!
