### ISSUE TITLE
Get rid of num_type?

### ISSUE THREAD

**Issue by Chris00** [mmottl/lacaml#30]
When using Merlin, types such as `Lacaml_float64.num_type` pop up instead of `float` which make signatures harder to read.  Since we already perform substitutions, how about to remove it (the `type num_type` would remain)?  This would be done in the "public" `.mli` files only.

**Comment by mmottl** [comment]
That's one possible solution.  Alternatively we could just use type substitution in places where signatures are referenced or included, e.g.:

```ocaml
include ... with type num_type := float
type num_type = float
```

The above trick removes type `num_type` from the included signature, substituting the appropriate concrete type wherever needed in the whole signature.  Then we reintroduce the type for backward compatibility, but it won't be referenced anymore from within the signature.

**Comment by Chris00** [comment]
In the interface files, the submodules are not included but their interface copied, mostly to ease reading the documentation in the file itself.  The only place where that could be done would be when doing `module D = Lacaml_D`.

**Comment by mmottl** [comment]
Ah, right, I remember.  I guess one could still do something of the sort:

```ocaml
module M : sig
  include sig
    (* verbatim definitions *)
  end with type num_type := float

  type num_type = float
end
```

Feel free to use whatever approach seems easier or more elegant to you.
