### ISSUE TITLE
documentation: functions which modify their input

### ISSUE THREAD

**Issue by nilsbecker** [mmottl/lacaml#31]
working with lapack is an exercise in general distrust. i just got bit again by `gesv a b` modifying `a`. for a seasoned fortran programmer this may be obvious, but it's in stark contrast to the ocaml paradigm of mostly immutable data. so from this point of view it's really more difficult to program in lacaml than in straight fortran: one is not generally in the mindset of pervasive mutability. 

anyway, the question is, what can lacaml do to help? for functions with a unit return value i am primed to expect that they modify something. for functions which give back a matrix, such as `gesv` i was not expecting it e.g. `gemm` leaves its input intact afaik. 

would it be sensible to state in the documentation, at least for functions with a nontrivial return value, what they may modify, if anything?

**Comment by mmottl** [comment]
Lacaml was originally designed as a more or less direct interface to BLAS/LAPACK and clearly documents that users should consult the corresponding documentation.  I agree that the semantics may not be quite what a functional programmer would expect, but it also ensures optimal performance.  Otherwise we'd have to create a lot of temporary copies of (potentially large) data.

Note that even `gemm` is not purely functional: you can optionally pass in a result matrix so it doesn't have to be allocated each time.  Note that you also cannot multiply two matrices and store the result in the same place as one of the arguments.  The result would not be correct.

Allocations of bigarrays can be pretty darn expensive.  It would have a significant performance impact on many practical programs if we tried to make Lacaml more "purely functional".

**Comment by nilsbecker** [comment]
i agree of course that rewriting everything to make functions pure would be nonsene for lacaml. that's fine. also, i agree that the lapack documentation is clear about what is going on with mutability. 

i was just thinking beyond pointing to the lapack documentation, lacaml could have some extra obvious CAVEAT in the documentation. if it's really the case that essentially any lapack/blas function (except lacpy..) will for some combination of arguments modify the input, then of course it does not make sense to document that everywhere.

maybe it would nonetheless be helpful to put a short paragraph about mutability in the intro?

**Comment by mmottl** [comment]
`lacpy`, too, is not purely functional and can lead to problems when not used wisely.  It also allows passing a result argument.  If, for example, the source and target range of the copy operation overlap, the result could be inconsistent.  There is no good, efficient way to deal with this without some semantic (purely functional) sacrifices.

If the semantics bothers you, I'd recommend creating an intermediate library that drops the somewhat cryptic BLAS/LAPACK function names in favor of more intuitive ones and saner (though likely less efficient) semantics.  That way you could also use different computational backends (e.g. Eigen, etc.).

**Comment by nilsbecker** [comment]
i think that's what owl is trying to be. i'm looking forward to trying that when it matures a bit.

**Comment by nilsbecker** [comment]
one last question: in the lapack documentation on netlib.org, argument intent is marked as [in] or [out] or both. 
if i pass a vector or an array to a lacaml function, and i pass it only in arguments that are marked as [in] in the corresponding lapack function, can i be certain that my vector/array is not modified?

**Comment by mmottl** [comment]
Nothing can prevent a user from passing the same or overlapping arguments to both `out` and `in` arguments.  Therefore, there is no guarantee that arguments will remain the same.

Lets take, for example, the `gemv` function: it multiplies a matrix and a vector.  This might suggest that at least the matrix will not be modified, but that's not true.  If I execute `gemv ~y:(Mat.col a 42) a x`, then a matrix column will be overwritten during the execution of this function and probably yield an inconsistent result.

Imperative updates are inherently tricky to reason about, especially if arguments can overlap.  Limiting functionality to disallow such scenarios often limits permissible use cases.  E.g. I might want to store the result vector adjacent to the argument matrix for mathematical / algorithmic reasons.

**Comment by nilsbecker** [comment]
thanks for the explanation; this makes a lot of sense.

i actually wanted to ask about a very restricted case. let's say i have matrices a,b,c. i know they do not overlap. now i call a lapack function fxyz, let's say `let result = fxyz ~a ~b ~c`. from the lapack docs i now that A and B have intent [in] while C is [in+out].  is this enough to tell me that in this specific invocation, e.g. a is not modified? 

as a concrete example: gemm has A and B as [in] and C as [in+out]. as long as i do not pass any parts of a or b into ~c, will a and b be preserved?

**Comment by mmottl** [comment]
If arguments marked as `in` only do not overlap with anything marked as `out`, they will not be modified.  Note that it's perfectly ok to pass the same value as `in` and `out` argument as long as the accessed regions do not overlap.  This is important for implementing some block algorithms.

**Comment by nilsbecker** [comment]
ok, got it. this was the piece of information that i was missing. note to self: always check the ins and outs :)
