### ISSUE TITLE
Vec.multiply_const ? 

### ISSUE THREAD

**Issue by nilsbecker** [mmottl/lacaml#33]
i could not find something like this. would this be a worthwhile addition (analogous to add_const)?

**Comment by mmottl** [comment]
There is `Mat.scal`, which will call BLAS `scal` internally and should hence be extremely fast.  Note, however, that this is an in-place operation.  Many operations would benefit from support for constants.  Another possibility would be to support tensor operations with broadcasting.

The `Lacaml` API evolved slowly over a long time and was initially based exclusively on BLAS/LAPACK operations.  The BLAS/LAPACK APIs are a little dated design-wise, but on the upside they are highly portable and extremely well tested as well as optimized on all platforms.  I hope a better low-level C or Fortran library will emerge eventually that offers broader functionality, including more of the commonly used unary and binary operations.

**Comment by nilsbecker** [comment]
actually, i knew about `Mat.scal`, i was interested in something similar for vectors.

**Comment by Chris00** [comment]
It is just `scal`.

**Comment by mmottl** [comment]
Yeah, it's one of those API quirks that arose from the historical ties to BLAS/LAPACK.  It would certainly be possible to add `Vec.scal` and maybe even deprecate the BLAS-function in the `D`-module.

**Comment by nilsbecker** [comment]
d'oh. actually i also spent some time not finding `copy` a while ago...
