### ISSUE TITLE
testing for Mat.empty

### ISSUE THREAD

**Issue by nilsbecker** [mmottl/lacaml#39]
what's the best way to test if a matrix is the empty matrix? is `a == Mat.empty` safe? should one test for the dimensions being 0?

**Comment by Chris00** [comment]
`==` is definitely not safe because it means "_have the same location in memory_".  Better go for the dimensions.

**Comment by nilsbecker** [comment]
i have been using `a = Mat.empty` which seemed to work but i'm also not sure about it. maybe the dimensions are indeed safest.

**Comment by mmottl** [comment]
`a = Mat.empty` is safe and efficient.  It relies on the comparison functions coming with the standard Bigarray module, which check the bigarray kind and layout, dimensions, and contents in that order.
