### ISSUE TITLE
Vec.ssqr returns incorrect results in 10.0.1 and 11.0.0

### ISSUE THREAD

**Issue by berke** [mmottl/lacaml#40]
Hi,

After upgrading from 7.2.1 to 11.0.0 (and adjusting the axpy labeled argument issues) I ran into a nasty bug: Vec.ssqr returns incorrect results.  This is with OCaml 4.05.0 as well as 4.05.0+trunk+flambda.

I thought this could be a boxing/unboxing issue, but the `@unboxed` annotation seems to be there for the return value in the generated `.ml`'s.

In the meantime we'll be using 9.3.2 which doesn't have this problem.

[test_lapack.zip](https://github.com/mmottl/lacaml/files/2032255/test_lapack.zip)

```ocaml
open Lacaml.D

let test_ssqr () =
  for k = 1 to 1000 do
    let n = 1 + Random.int 100 in
    let v = Vec.create n in
    for j = 1 to n do
      v.{j} <- Random.float 1.0 -. 0.5
    done;
    let ss = ref 0.0 in
    for j = 1 to n do
      ss := !ss +. v.{j} *. v.{j}
    done;
    let ss' = Vec.ssqr v in
    let err = abs_float (!ss -. ss') in
    let tol = float n *. epsilon_float in
    if err > tol then failwith (Printf.sprintf "test_ssqr: err=%g > tol=%g" err tol)
  done

let _ = test_ssqr ()
```

**Comment by mmottl** [comment]
Thanks for the bug report!  The fix was trivial, but the problem (an incorrect type in an `extern` C-declaration) was hard to spot.
