### ISSUE TITLE
Onilne API is down

### ISSUE THREAD

**Issue by scemama** [mmottl/lacaml#41]
Hello,
your online API is down:

http://mmottl.github.io/lacaml/api/lacaml

Error 404 Page not found

Best,
Anthony

**Comment by mmottl** [comment]
Thanks for the report, the problem is now fixed.  This is the same issue as https://github.com/mmottl/sqlite3-ocaml/issues/30.

**Comment by scemama** [comment]
Thank you for fixing this.
And thank you for Lacaml, which is VERY helpful!

**Comment by mmottl** [comment]
Thanks for the feedback!
