### ISSUE TITLE
OPAM with MKL

### ISSUE THREAD

**Issue by scemama** [mmottl/lacaml#42]
Hi,
I have succeeded to use lacaml with the Intel MKL library on my desktop PC by doing : 

```bash
export  LACAML_LIBS="-L${MKLROOT}/lib/intel64 -Wl,--no-as-needed -lmkl_rt -lpthread -lm -ldl"
opam install lacaml
```

but when I tried on a HPC server, it did not work because on that particular machine there is no libblas.so and liblapack.so. Only the MKL is available. So the installation of conf-blas and conf-lapack fails.

I am not familiar with opam configuration files, so I can't fix the conf-* files myself and submit a pull request, but I could force the installation by doing the following symbolic links in a directory which is in my `LIBRARY_PATH`:

```
ln -s $MKLROOT/lib/intel64/libmkl_rt.so libblas.so
ln -s $MKLROOT/lib/intel64/libmkl_rt.so liblapack.so
```

cheers,

Anthony

**Comment by mmottl** [comment]
@scemama Thanks for explaining what flags to pass to make `lacaml` work with Intel MKL, this might help other MKL users.  It seems unfortunate that your platform doesn't provide for the more standard `libblas` and `liblapack` libraries even though MKL is compatible.  Not sure whether the MKL installation could be configured to install these libraries or links.

I have just submitted improved OPAM packages for `conf-blas` and `conf-lapack`.  The big difference is that they now also support `LACAML_LIBS`.  This should allow users to install them without using your link hack.  Could you please try them out once they appear in the public OPAM repository?

**Comment by scemama** [comment]
@mmottl OK, thank you for your quick reply. I am pretty sure it will work.
